package org.example.backendweride.platform.booking.interfaces.resources;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * CreateBookingResource record representing ALL the data needed to create a booking.
 *
 * @summary This record allows the user to provide all booking details.
 *          The database ID and bookingId are auto-generated by the system.
 */
public record CreateBookingResource(
    Long userId,
    Long vehicleId,
    Long startLocationId,
    Long endLocationId,
    LocalDateTime reservedAt,
    LocalDateTime startDate,
    LocalDateTime endDate,
    LocalDateTime actualStartDate,
    LocalDateTime actualEndDate,
    String status,
    BigDecimal totalCost,
    BigDecimal discount,
    BigDecimal finalCost,
    String paymentMethod,
    String paymentStatus,
    Double distance,
    Integer duration,
    Double averageSpeed,
    RatingResource rating
) { }
