package org.example.backendweride.platform.booking.interfaces.resources;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * SaveBookingDraftResource record representing the data needed to save a booking draft.
 *
 * @summary This record encapsulates all the information for saving a draft booking.
 *          The database ID and bookingId are auto-generated by the system.
 */
public record SaveBookingDraftResource(
    Long userId,
    Long vehicleId,
    Long startLocationId,
    Long endLocationId,
    LocalDateTime reservedAt,
    LocalDateTime startDate,
    LocalDateTime endDate,
    LocalDateTime actualStartDate,
    LocalDateTime actualEndDate,
    String status,
    BigDecimal totalCost,
    BigDecimal discount,
    BigDecimal finalCost,
    String paymentMethod,
    String paymentStatus,
    Double distance,
    Integer duration,
    Double averageSpeed,
    RatingResource rating
) { }

